name: 02 - Workflow Events

on: 
    # schedule:
    #     - cron: "15 4,5 * * *"
    - push
    - workflow_dispatch
    - pull_request

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: |
                echo "Event name: ${{ github.event_name }}"

        